-- Schema Backup: Functions, Constraints, Types
-- Generated: 2025-09-02T20:15:13.617Z

-- No custom functions found

-- Constraints
ALTER TABLE _migrations ADD CONSTRAINT 2200_27098_1_not_null CHECK;
ALTER TABLE _migrations ADD CONSTRAINT 2200_27098_2_not_null CHECK;
ALTER TABLE _migrations ADD CONSTRAINT 2200_27098_3_not_null CHECK;
ALTER TABLE _migrations ADD CONSTRAINT _migrations_name_key UNIQUE;
ALTER TABLE challenge_jury ADD CONSTRAINT 2200_27204_1_not_null CHECK;
ALTER TABLE challenge_jury ADD CONSTRAINT challenge_jury_challenge_id_fkey FOREIGN KEY;
ALTER TABLE challenge_jury ADD CONSTRAINT challenge_jury_user_id_fkey FOREIGN KEY;
ALTER TABLE challenge_jury ADD CONSTRAINT unique_jury_per_challenge UNIQUE;
ALTER TABLE challenge_participations ADD CONSTRAINT 2200_27227_1_not_null CHECK;
ALTER TABLE challenge_participations ADD CONSTRAINT 2200_27227_2_not_null CHECK;
ALTER TABLE challenge_participations ADD CONSTRAINT 2200_27227_3_not_null CHECK;
ALTER TABLE challenge_participations ADD CONSTRAINT challenge_participations_challenge_id_fkey FOREIGN KEY;
ALTER TABLE challenge_participations ADD CONSTRAINT challenge_participations_challenge_id_user_id_key UNIQUE;
ALTER TABLE challenge_participations ADD CONSTRAINT challenge_participations_user_id_fkey FOREIGN KEY;
ALTER TABLE challenge_votes ADD CONSTRAINT 2200_27249_1_not_null CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT 2200_27249_5_not_null CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT 2200_27249_8_not_null CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_challenge_id_fkey FOREIGN KEY;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_interpretation_points_check CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_originalite_points_check CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_participation_id_fkey FOREIGN KEY;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_points_check CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_technique_points_check CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_vote_type_check CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT challenge_votes_voter_id_fkey FOREIGN KEY;
ALTER TABLE challenge_votes ADD CONSTRAINT jury_vote_criteria_required CHECK;
ALTER TABLE challenge_votes ADD CONSTRAINT unique_vote_per_participation UNIQUE;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_13_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_19_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_1_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_21_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_2_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_3_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_4_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_8_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT 2200_26994_9_not_null CHECK;
ALTER TABLE challenges ADD CONSTRAINT challenges_user_id_fkey FOREIGN KEY;
ALTER TABLE challenges ADD CONSTRAINT challenges_user_id_profiles_fkey FOREIGN KEY;
ALTER TABLE challenges ADD CONSTRAINT challenges_voting_type_check CHECK;
ALTER TABLE challenges ADD CONSTRAINT challenges_winner_uid_fkey FOREIGN KEY;
ALTER TABLE challenges_medias ADD CONSTRAINT 2200_27182_1_not_null CHECK;
ALTER TABLE challenges_medias ADD CONSTRAINT 2200_27182_2_not_null CHECK;
ALTER TABLE challenges_medias ADD CONSTRAINT 2200_27182_3_not_null CHECK;
ALTER TABLE challenges_medias ADD CONSTRAINT 2200_27182_4_not_null CHECK;
ALTER TABLE challenges_medias ADD CONSTRAINT challenges_medias_challenge_id_fkey FOREIGN KEY;
ALTER TABLE challenges_medias ADD CONSTRAINT challenges_medias_media_id_fkey FOREIGN KEY;
ALTER TABLE challenges_medias ADD CONSTRAINT unique_challenge_media UNIQUE;
ALTER TABLE challenges_medias ADD CONSTRAINT unique_challenge_media_position UNIQUE;
ALTER TABLE comments ADD CONSTRAINT 2200_27109_1_not_null CHECK;
ALTER TABLE comments ADD CONSTRAINT 2200_27109_2_not_null CHECK;
ALTER TABLE comments ADD CONSTRAINT 2200_27109_3_not_null CHECK;
ALTER TABLE comments ADD CONSTRAINT 2200_27109_4_not_null CHECK;
ALTER TABLE comments ADD CONSTRAINT 2200_27109_6_not_null CHECK;
ALTER TABLE comments ADD CONSTRAINT comments_challenge_id_fkey FOREIGN KEY;
ALTER TABLE comments ADD CONSTRAINT comments_media_id_fkey FOREIGN KEY;
ALTER TABLE comments ADD CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY;
ALTER TABLE comments ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY;
ALTER TABLE comments ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY;
ALTER TABLE daily_comments ADD CONSTRAINT 2200_27143_1_not_null CHECK;
ALTER TABLE daily_comments ADD CONSTRAINT daily_comments_comment_id_fkey FOREIGN KEY;
ALTER TABLE daily_comments ADD CONSTRAINT daily_comments_user_id_fkey FOREIGN KEY;
ALTER TABLE daily_media_uploads ADD CONSTRAINT 2200_27162_1_not_null CHECK;
ALTER TABLE daily_media_uploads ADD CONSTRAINT daily_media_uploads_media_id_fkey FOREIGN KEY;
ALTER TABLE daily_media_uploads ADD CONSTRAINT daily_media_uploads_user_id_fkey FOREIGN KEY;
ALTER TABLE daily_media_uploads ADD CONSTRAINT daily_media_uploads_user_id_upload_date_key UNIQUE;
ALTER TABLE follows ADD CONSTRAINT 2200_27392_1_not_null CHECK;
ALTER TABLE follows ADD CONSTRAINT 2200_27392_2_not_null CHECK;
ALTER TABLE follows ADD CONSTRAINT 2200_27392_3_not_null CHECK;
ALTER TABLE follows ADD CONSTRAINT follows_follower_id_fkey FOREIGN KEY;
ALTER TABLE follows ADD CONSTRAINT follows_following_id_fkey FOREIGN KEY;
ALTER TABLE follows ADD CONSTRAINT follows_no_self_follow CHECK;
ALTER TABLE follows ADD CONSTRAINT follows_unique UNIQUE;
ALTER TABLE interactions ADD CONSTRAINT 2200_27297_1_not_null CHECK;
ALTER TABLE interactions ADD CONSTRAINT 2200_27297_2_not_null CHECK;
ALTER TABLE interactions ADD CONSTRAINT 2200_27297_3_not_null CHECK;
ALTER TABLE interactions ADD CONSTRAINT 2200_27297_4_not_null CHECK;
ALTER TABLE interactions ADD CONSTRAINT interactions_challenge_id_fkey FOREIGN KEY;
ALTER TABLE interactions ADD CONSTRAINT interactions_comment_id_fkey FOREIGN KEY;
ALTER TABLE interactions ADD CONSTRAINT interactions_media_id_fkey FOREIGN KEY;
ALTER TABLE interactions ADD CONSTRAINT interactions_post_id_fkey FOREIGN KEY;
ALTER TABLE interactions ADD CONSTRAINT interactions_user_id_fkey FOREIGN KEY;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_10_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_11_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_1_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_2_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_3_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_4_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_5_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT 2200_27033_6_not_null CHECK;
ALTER TABLE medias ADD CONSTRAINT medias_user_id_fkey FOREIGN KEY;
ALTER TABLE medias ADD CONSTRAINT valid_cover_url CHECK;
ALTER TABLE points_history ADD CONSTRAINT 2200_27376_1_not_null CHECK;
ALTER TABLE points_history ADD CONSTRAINT 2200_27376_3_not_null CHECK;
ALTER TABLE points_history ADD CONSTRAINT 2200_27376_4_not_null CHECK;
ALTER TABLE points_history ADD CONSTRAINT points_history_user_id_fkey FOREIGN KEY;
ALTER TABLE post_participations ADD CONSTRAINT 2200_27355_1_not_null CHECK;
ALTER TABLE post_participations ADD CONSTRAINT 2200_27355_2_not_null CHECK;
ALTER TABLE post_participations ADD CONSTRAINT 2200_27355_3_not_null CHECK;
ALTER TABLE post_participations ADD CONSTRAINT post_participations_post_id_fkey FOREIGN KEY;
ALTER TABLE post_participations ADD CONSTRAINT post_participations_user_id_fkey FOREIGN KEY;
ALTER TABLE posts ADD CONSTRAINT 2200_27052_1_not_null CHECK;
ALTER TABLE posts ADD CONSTRAINT 2200_27052_2_not_null CHECK;
ALTER TABLE posts ADD CONSTRAINT 2200_27052_3_not_null CHECK;
ALTER TABLE posts ADD CONSTRAINT 2200_27052_5_not_null CHECK;
ALTER TABLE posts ADD CONSTRAINT 2200_27052_6_not_null CHECK;
ALTER TABLE posts ADD CONSTRAINT posts_challenge_id_fkey FOREIGN KEY;
ALTER TABLE posts ADD CONSTRAINT posts_profiles_fkey FOREIGN KEY;
ALTER TABLE posts_medias ADD CONSTRAINT 2200_27075_1_not_null CHECK;
ALTER TABLE posts_medias ADD CONSTRAINT 2200_27075_2_not_null CHECK;
ALTER TABLE posts_medias ADD CONSTRAINT 2200_27075_3_not_null CHECK;
ALTER TABLE posts_medias ADD CONSTRAINT 2200_27075_4_not_null CHECK;
ALTER TABLE posts_medias ADD CONSTRAINT 2200_27075_5_not_null CHECK;
ALTER TABLE posts_medias ADD CONSTRAINT posts_medias_media_id_fkey FOREIGN KEY;
ALTER TABLE posts_medias ADD CONSTRAINT posts_medias_post_id_fkey FOREIGN KEY;
ALTER TABLE posts_medias ADD CONSTRAINT unique_post_media UNIQUE;
ALTER TABLE posts_medias ADD CONSTRAINT unique_post_media_position UNIQUE;
ALTER TABLE profiles ADD CONSTRAINT 2200_26938_1_not_null CHECK;
ALTER TABLE profiles ADD CONSTRAINT 2200_26938_26_not_null CHECK;
ALTER TABLE profiles ADD CONSTRAINT phone_format CHECK;
ALTER TABLE profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY;
ALTER TABLE profiles_beatmakers ADD CONSTRAINT 2200_26968_1_not_null CHECK;
ALTER TABLE profiles_beatmakers ADD CONSTRAINT activities_is_array CHECK;
ALTER TABLE profiles_beatmakers ADD CONSTRAINT phone_format CHECK;
ALTER TABLE profiles_beatmakers ADD CONSTRAINT profiles_beatmakers_id_fkey FOREIGN KEY;
ALTER TABLE unique_likes ADD CONSTRAINT 2200_27336_1_not_null CHECK;
ALTER TABLE unique_likes ADD CONSTRAINT unique_likes_media_id_fkey FOREIGN KEY;
ALTER TABLE unique_likes ADD CONSTRAINT unique_likes_media_id_user_id_key UNIQUE;
ALTER TABLE unique_likes ADD CONSTRAINT unique_likes_user_id_fkey FOREIGN KEY;
ALTER TABLE users_to_clean ADD CONSTRAINT 2200_27418_1_not_null CHECK;
ALTER TABLE weekly_rankings ADD CONSTRAINT 2200_27714_1_not_null CHECK;
ALTER TABLE weekly_rankings ADD CONSTRAINT weekly_rankings_user_id_fkey FOREIGN KEY;
ALTER TABLE weekly_rankings ADD CONSTRAINT weekly_rankings_user_id_week_start_key UNIQUE;

